---
title: "TP4"
author: "Yanis Micha"
format: html
---

# Exercice 1: courbes ROC
```{r}
require(ROCR)
require(ggplot2)
library(pROC)
load("DataTp4/tp-4_exo-1.Rdata")
```

```{r}
data
```

## 2
```{r}
for(i in 1:3){
  data[[paste0("cat",i)]] <- ifelse(data[[paste0("score",i)]]>=0,1,0)
}
TP <- nrow(data[data$label==1 & data$cat1==1,])
FP <- nrow(data[data$label==0 & data$cat1==1,])
TN <- nrow(data[data$label==0 & data$cat1==0,])
FN <-  nrow(data[data$label==1 & data$cat1==0,])
cont1 <- table(data$label,data$cat1)
cont2 <- table(data$label,data$cat2)
cont3 <- table(data$label,data$cat3)
sensi1 <- cont1[2,2]/(cont1[2,2]+cont1[2,1])
sensi2 <- cont2[2,2]/(cont2[2,2]+cont2[2,1])
sensi3 <- cont3[2,2]/(cont3[2,2]+cont3[2,1])
speci1 <- cont1[1,1]/(cont1[1,1]+cont1[1,2])
speci2 <- cont2[1,1]/(cont2[1,1]+cont2[1,2])
speci3 <- cont3[1,1]/(cont3[1,1]+cont3[1,2])

for(i in 1:3){
  cat("*** Sensibilité du",i,ifelse(i==1,"er","eme"),"classifieur:", get(paste0("sensi",i))*100,"%","***\n")
  cat("*** Spécificité du",i,ifelse(i==1,"er","eme"),"classifieur:",get(paste0("speci",i))*100,"%","***\n")
}
caret::confusionMatrix(as.factor(data$label),as.factor(data$cat1))
```

## 3 courbes ROC 

```{r}
pred1 <- prediction(data$score1,data$label, label.ordering = c(0,1))
pred2 <- prediction(data$score2,data$label, label.ordering = c(0,1))
pred3 <- prediction(data$score3,data$label, label.ordering = c(0,1))
perf.roc = performance(pred1, measure = "tpr", x.measure
= "fpr")
plot(perf.roc, main = "ROC curve")
roc.df <- data.frame(fpr = perf.roc@x.values[[1]], tpr = perf.roc@y.values[[1]])
fig <- ggplot(roc.df,aes(x = fpr, y = tpr)) +
  geom_line(color="steelblue") +
  geom_point(x = 1-speci1,y=sensi1,color="steelblue")+
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  labs(x = "Taux de faux positifs", y = "Taux de vrais positifs", title = "Courbe ROC")

for(i in c(2,3)){
  perf.roc = performance(get(paste0("pred",i)), measure = "tpr", x.measure
= "fpr")
  roc.df <- data.frame(fpr = perf.roc@x.values[[1]], tpr = perf.roc@y.values[[1]])
  fig <- fig+
    geom_line(data = roc.df,aes(x = fpr, y = tpr),color=i)+
    geom_point(x = 1-get(paste0("speci",i)),y = get(paste0("sensi",i)),color=i)
}
fig
perf.auc = performance(pred1, measure = "auc")
auc = perf.auc@y.values[[1]]

```

## 5
```{r}
fig+geom_vline(xintercept = 1-speci1,color="steelblue")+geom_hline(yintercept = sensi1,color="steelblue")
fig+geom_vline(xintercept = 1-0.75,color="chartreuse")+geom_hline(yintercept = 0.75,color="darkorange")
ggroc(roc(data$label,data$score1),colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))


```


# Exercice 2 : classification par k plus proches voisins
```{r}
require(class)
rm(list=ls())
load("DataTp4/tp-4_exo-2.Rdata")

set.seed(27) # afin d’avoir toutes et tous le même découpage
ind.val = sample(length(y), 2000)
X.val = X[ind.val,]
y.val = y[ind.val]
X.train = X[-ind.val,]
y.train = y[-ind.val]
```

```{r cache=TRUE}
acc.val <- rep(0,10)
for(i in 1:10){
  cat("************ Matrice de confusion pour k = ",i,"*************\n")
  knnPred= knn(X.train,X.val,y.train,k=i,prob=TRUE)
  print(table(knnPred,y.val))
  preds.val = knn(X.train, X.val, y.train, k = k)
  acc.val[i] = mean(preds.val == y.val)
  cat("*************************************************************\n")
}
```

```{r}
library(caret)
#train(y.test ~.,method = "knn",)
k.best = (1:10)[which.max(acc.val)]
knnPred= knn(X,X.test,y,k=1,prob=TRUE)
table(knnPred,y.test)
acc.test=mean(knnPred== y.test)
cat("***** Accuracy measured on test data=",acc.test*100,"% *****")
#expand.grid()
```

## 5 
```{r,cache = TRUE}
conf <- table(knnPred,y.test)
dt <- data.frame(conf)
pred.correct <-  y.test == knnPred
tt = split(pred.correct,y.test)
acc.digit=sapply(tt,mean)
barplot(acc.digit,col=factor(knnPred))

df <- data.frame(x = 0:9, y = acc.digit)

df <- df[order(df$y), ]

# Créer un graphique à barres avec ggplot en utilisant le data frame trié
ggplot(df, aes(x = factor(x), y = y, fill = y)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "steelblue", high = "darkblue") +  
  labs(x = "Chiffres", y = "Proportion bien classés")
```










